INSERT INTO TBL_CLIENT (ID, NAME, BALANCE) VALUES (10, 'CLIENT 1',100);
INSERT INTO TBL_CLIENT (ID, NAME, BALANCE) VALUES (20, 'CLIENT 2',200);
INSERT INTO TBL_CLIENT (ID, NAME, BALANCE) VALUES (30, 'CLIENT 3',300);
